export enum ContentType {
  ENROLL_V1 = 'application/vnd.ncryptyr.enroll.v1+json',
  ENROLL_V1_RESPONSE = 'application/vnd.ncryptyr.enroll-response.v1+json',
  DESCRIBE_ACCOUNT_V1 = 'application/vnd.ncryptyr.describe-account.v1+json',
  DESCRIBE_ACCOUNT_V1_RESPONSE = 'application/vnd.ncryptyr.describe-account-response.v1+json',
  LIST_ACCOUNTS_V1 = 'application/vnd.ncryptyr.list-accounts.v1+json',
  LIST_ACCOUNTS_V1_RESPONSE = 'application/vnd.ncryptyr.list-accounts-response.v1+json',
  UPDATE_ACCOUNT_V1 = 'application/vnd.ncryptyr.update-account.v1+json',
  UPDATE_ACCOUNT_V1_RESPONSE = 'application/vnd.ncryptyr.update-account-response.v1+json',
  DELETE_ACCOUNT_V1 = 'application/vnd.ncryptyr.delete-account.v1+json',
  CREATE_API_KEY_V1 = 'application/vnd.ncryptyr.create-api-key.v1+json',
  CREATE_API_KEY_V1_RESPONSE = 'application/vnd.ncryptyr.create-api-key-response.v1+json',
  LIST_API_KEYS_V1 = 'application/vnd.ncryptyr.list-api-keys.v1+json',
  LIST_API_KEYS_V1_RESPONSE = 'application/vnd.ncryptyr.list-api-keys-response.v1+json',
  DELETE_API_KEY_V1 = 'application/vnd.ncryptyr.delete-api-key.v1+json',
  CREATE_ENCRYPTION_KEY_V1 = 'application/vnd.ncryptyr.create-encryption-key.v1+json',
  CREATE_ENCRYPTION_KEY_V1_RESPONSE = 'application/vnd.ncryptyr.create-encryption-key-response.v1+json',
  DESCRIBE_ENCRYPTION_KEY_V1 = 'application/vnd.ncryptyr.describe-encryption-key.v1+json',
  DESCRIBE_ENCRYPTION_KEY_V1_RESPONSE = 'application/vnd.ncryptyr.describe-encryption-key-response.v1+json',
  EXPORT_ENCRYPTION_KEY_V1 = 'application/vnd.ncryptyr.export-encryption-key.v1+json',
  EXPORT_ENCRYPTION_KEY_V1_RESPONSE = 'application/vnd.ncryptyr.export-encryption-key-response.v1+json',
  LIST_ENCRYPTION_KEYS_V1 = 'application/vnd.ncryptyr.list-encryption-keys.v1+json',
  LIST_ENCRYPTION_KEYS_V1_RESPONSE = 'application/vnd.ncryptyr.list-encryption-keys-response.v1+json',
  DELETE_ENCRYPTION_KEY_V1 = 'application/vnd.ncryptyr.delete-encryption-key.v1+json',
}
