  on:
    push:
      branches:
        - main
        - develop
  name: ci
  jobs:
    publish:
      uses: nr1etech/github-workflows/.github/workflows/javascript-library.yml@main
      with:
        github-email: "365211+erikrj@users.noreply.github.com"
        github-name: "Erik Jensen"
      secrets:
        deploy-key: ${{ secrets.DEPLOY_KEY }}
        npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
