  on:
    workflow_call:
      push:
        branches:
          - main
          - develop
  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18, 20]
          registry-url: [https://registry.npmjs.org/, https://npm.pkg.github.com/]
      steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        - name: Install Dependencies
          run: pnpm i --frozen-lockfile --prefer-offline
        - name: Increment alpha version
          if: github.ref == 'refs/heads/develop'
          run: echo VERSION="$(pnpm version prepatch --preid alpha --no-git-tag-version)" >> $GITHUB_ENV
        - name: Increment patch version
          if: github.ref == 'refs/heads/main'
          run: echo VERSION="$(pnpm version patch --no-git-tag-version)" >> $GITHUB_ENV
        - name: Build
          run: pnpm build
        - name: Test
          run: pnpm test
        - name: Commit
          if: github.matrix.node-version == 20
          run: |
            git commit -a -m "$VERSION"
            git push
        - name: Tag Release
          if: github.matrix.node-version == 20 && github.ref == 'refs/heads/main'
          run: |
            git tag -a "$VERSION" -m "$VERSION"
            git push origin "$VERSION"
        - name: Publish
          if: github.matrix.node-version == 20
          run: pnpm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
